###
POST http://localhost:8080/api/v1/fruit
Content-Type: application/json

{
    "name": "apple",
    "warehousingDate": "2024-01-01",
    "price": 1003
}

###
PUT http://localhost:8080/api/v1/fruit
Content-Type: application/json

{
    "id": 1
}

###
GET http://localhost:8080/api/v1/fruit/stat?name=apple


###
GET http://localhost:8080/api/v1/fruit/count?name=apple


###
GET http://localhost:8080/api/v1/fruit/list?option=LTE&price=9000
